name: format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cpp-linter/cpp-linter-action@v2
      id: cpp-lint
      with:
        style: file
        tidy-checks: '-*' # disable clang tidy at this stage
        version: 17
    - name: Fail test
      if: steps.cpp-lint.outputs.checks-failed > 0
      run: echo "Some files failed the linting checks!" && exit 1

  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with: # see: https://black.readthedocs.io/en/stable/getting_started.html
          version: "~= 23.11.0"
